# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "wscffaa"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 50

publish_readme: True
publish_gitpage: False
publish_wechat: False

keywords:
    "360 Super-Resolution":
        filters: [ "omnidirectional Super-Resolution", "omnidirectional Image Super-Resolution", "omnidirectional Video Super-Resolution" ]
    "Diffusion-Models":
        filters: ["Diffusion Models"]
    "Super-Resolution":
        filters: ["SR", "Super-Resolution", "Super Resolution"]
    "Image-Super-Resolution":
        filters: ["SISR", "Image Super Resolution"]
    "Video-Super-Resolution":
        filters: ["VSR", "Video Super Resolution"]
    "Image-Colorization":
        filters: ["Image-Colorization", "Image Colorization"]
    "Video-Colorization":
        filters: ["Video-Colorization","Video Colorization"]
    "Image Restoration":
        filters: ["Image Restoration"]
    "Image Reconstruction":
        filters: ["Image Reconstruction"]
    "Image Denoising":
        filters: ["Image Denoising"]
    "Image Inpainting":
        filters: ["Image Inpainting"]
    "Style Transfer":
        filters: ["Style Transfer"]